### ISSUE TITLE
new callback when cipher successfully created (store not invalidated)

### ISSUE THREAD

**Issue by okalman** [infinum/Android-Goldfinger#31]
Hi, it would be great to have callback when cipher was successfully created . Because alomst everyone wants to show dialog with fingerprint only when everything is ready. Current implementation will give you on error but this way you have to show dialog in advance and then dismiss it when  onError is called. This doesn't look very good on UI. Only workaround is to implement own CryptoFactory and call  cryptoObjectFactory.createDecryptionCryptoObject(this.storageKey) somewhere outside (to check whether store is not invalidated)

**Comment by domagojkorman** [comment]
Hi, this is an awesome suggestion. I already had some changes in mind for FingerprintCallback and I will definitely include this suggestion.

Thank you for opening an issue.
