### ISSUE TITLE
Deleting all fingerprints from device

### ISSUE THREAD

**Issue by mariciv** [infinum/Android-Goldfinger#45]
Most devices invalidate fingerprint and we should get an error next time we try to start fingerprint reading. But on some device like LG G5 and OnePlus2 this doesn't happen. Instead we get onReady callback even though we definitely can't get a successful auth result cause there is no fingerprint to match. 

A quick fix in any project is to check if there are enrolled fingerprints before trying to start fingerprint reading but maybe we could push this inside the lib so we expose this error consistently.

**Comment by domagojkorman** [comment]
Agreed. We shall add the check before authentiocation in next release.

**Comment by domagojkorman** [comment]
Fixed in v1.2.0. 

We check preconditions before starting the authentication and exception is thrown if user has no hardware or no enrolled fingerprints.

Closing issue.
