### ISSUE TITLE
Biometric prompt localisation

### ISSUE THREAD

**Issue by zplesac** [infinum/Android-Goldfinger#52]
We should check the Biometric prompt localisation - it seems that title, description and subtitle are localised using the app context, while the info message get's localised using the phone language. 
You can see [here](https://android.googlesource.com/platform/frameworks/support/+/b8de83833a365a0342a01630807c96f42e64782b/biometric/res/) that prompt is packed with localisation support for all languages.

This is resulting in a strange behaviour where half of the prompt is using one language, while other half is using something else.

**Comment by domagojkorman** [comment]
@zplesac 
I just tested this behavior inside Example activity and it seems like everything is working OK. Are you sure that the localization is correctly implemented inside your implementation?

This is what I used and everything worked smooth.
```java
    private Context updateLocale(Context context) {
        Configuration config = new Configuration(context.getResources().getConfiguration());
        Locale locale = Locale.FRENCH;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            config.setLocale(locale);
        } else {
            config.locale = locale;
        }

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            return context.createConfigurationContext(config);
        } else {
            context.getResources().updateConfiguration(config, context.getResources().getDisplayMetrics());
            return context;
        }
    }

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(updateLocale(newBase));
    }
```

**Comment by zplesac** [comment]
@davidvinf will check this with sample activity on his Huawei device and report back.

**Comment by domagojkorman** [comment]
I investigated this and it seems that it is device specific issue because localization correctly worked on 2, 3 different devices that I tested it on. Closing this issue as there is nothing that can be done, Goldfinger uses correct `Context`, and the reported string that is not controlled by Goldfinger.

**Comment by igotepava** [comment]
@zplesac I see that you are using appcompat 1.1.0 which has introduced an issue with applying locale on devices from API 21 to 25. Try downgrading to 1.0.2 and see if it works.
