### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by dpproduction** [infinum/Android-Goldfinger#64]
Please, add ability to change fingerprint icon.

**Comment by igotepava** [comment]
Hello @dpproduction, this is not supported by the `BiometricPrompt` in the support library. The dialog which is shown is system-provided, not a custom one. More info on params can be found in [our docs](https://github.com/infinum/Android-Goldfinger#build-params) or [the official support library docs](https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder.html).
